<h3 align="center">Paweł Kocimski </h3>
<h5 align="center">Metody Obliczeniowe w Nauce i Technice </h5>
<h6 align="center">Lab 8 PageRank</h6>



<h6>Prosty ranking wierzchołków</h6>
Zaimplementuj prosty model błądzenia przypadkowego po grafie skierowanym:


$$r(u)=d\sum_{v\in{B}_{u}} \frac{r(v)}{{N}_{v}}$$

In [149]:
import numpy as np

def random_walk(A, num_multiplications: int):

    eigen_vec = np.random.rand(A.shape[1])
    c = 0.5
    A = c*A
    
    for _ in range(num_multiplications):
        eigen_vec_2 = np.dot(A, eigen_vec) 
        eigen_vec = eigen_vec_2
        
    eigen_vec_2_norm = np.linalg.norm(eigen_vec_2)
    eigen_vec = eigen_vec_2 / eigen_vec_2_norm
    
    return eigen_vec



In [150]:
def test_random_walk():
    A = np.array([[0,0.5,0,0,0,0.5,0,0,0,0],
                 [0,0,0.5,0,0,0.5,0,0,0,0],
                 [0.5,0,0,0.5,0,0,0,0,0,0],
                 [0,0,0,0,0.5,0,0,0,0,0],
                 [0,0,0,0.5,0,0.5,0,0,0,0],
                 [0,0,0,0,0,0,0.5,0,0.5,0],
                 [0,0.5,0,0,0,0,0,0.5,0,0],
                 [0,0,0,0,0.5,0,0,0,0.5,0],
                 [0,0,0,0.5,0,0,0,0,0,0.5],
                 [0.5,0,0,0,0,0.5,0,0,0,0]])
    print(random_walk(A, 20))
    B = np.array([[0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                   [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                   [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                   [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                   [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                   [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                   [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                   [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                   [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                   [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                 ])
    print(random_walk(B, 20))
    C = np.array([[0,0.33,0,0,0.33,0,0,0.33,0,0],
                     [0,0,0.2,0,0,0.2,0,0.2,0.2,0.2],
                     [0,0,0,0.25,0,0.25,0,0.25,0,0],
                     [0,0,0,0,0.25,0.25,0.25,0,0.25,0],
                     [0,0.5,0,0,0,0.5,0,0,0,0],
                     [0,0,0,0,0.5,0,0.5,0,0,0],
                     [0,0,0,0,0,0.25,0.25,0.5,0.25,0],
                     [0.25,0,0,0.25,0,0.25,0,0,0.25,0],
                     [0,0,0,0,0.2,0.2,0,0.2,0,0.2],
                     [0.5,0,0,0,0,0,0,0,0.5,0]])
    print(random_walk(C, 20))
test_random_walk()

[0.37372706 0.34123664 0.28139579 0.14490733 0.26728107 0.34738584
 0.34951124 0.30276302 0.29097548 0.39127681]
[0.31622777 0.31622777 0.31622777 0.31622777 0.31622777 0.31622777
 0.31622777 0.31622777 0.31622777 0.31622777]
[0.30392867 0.28999239 0.25170419 0.33637457 0.3252331  0.3653119
 0.4108201  0.31261288 0.25413827 0.27697176]


<h6>Page Rank</h6>
Rozszerz model z poprzedniego zadania, dodając możliwość skoku do losowego wierz-
chołka grafu:

$$r(u)=d\sum_{v\in{B}_{u}} \frac{r(v)}{{N}_{v}} +(1-d)e(u)$$


In [151]:
def page_rank(A, e, epsilon, c):

    eigen_vec = np.random.rand(A.shape[1])
    A = c*A
    
    
    condition = True
    while condition:
        eigen_vec_2 = np.dot(A, eigen_vec)
        d = np.sum(eigen_vec) - np.sum(eigen_vec_2)
        eigen_vec_2 = eigen_vec_2 + (d * e)
        sigma = np.sum(np.subtract(eigen_vec_2, eigen_vec))
        condition = sigma > epsilon
        eigen_vec = eigen_vec_2
    
        
    eigen_vec_2_norm = np.linalg.norm(eigen_vec_2)
    eigen_vec = eigen_vec_2 / eigen_vec_2_norm

    return eigen_vec


In [169]:
def read_gnutella8():
    file1 = open('p2p-Gnutella08.txt', 'r') 
    Lines = file1.readlines() 
    gnutella = np.zeros((6301,6301))

    count = 0
   
    for line in Lines: 
        count +=1
        if(count >= 5):
            splited = line.split('\t')
            row = int(splited[0])
            column = int(splited[1])
            gnutella[row][column] = 1 
    
    for row in range(gnutella.shape[0]):
        sum_row = sum(gnutella[row])
        if(sum_row != 0):
            for i in range(gnutella.shape[0]):
                gnutella[row][i] /= sum_row
    
    return gnutella
    
    
        
read_gnutella8()

array([[0. , 0.1, 0.1, ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ]])

In [170]:
def read_gnutella9():
    file1 = open('p2p-Gnutella09.txt', 'r') 
    Lines = file1.readlines() 
    gnutella = np.zeros((8114,8114))
    count = 0

    for line in Lines: 
        count += 1
        if(count >= 5):
            splited = line.split('\t')   
            row = int(splited[0])
            column = int(splited[1])
            gnutella[row][column] = 1 
            
    
    for row in range(gnutella.shape[0]):
        sum_row = sum(gnutella[row])
        if(sum_row != 0):
            for i in range(gnutella.shape[0]):
                gnutella[row][i] /= sum_row
                
    return gnutella

read_gnutella9()

array([[0. , 0.1, 0.1, ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 0.2],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ]])

In [171]:
def test_page_rank():
    gnutella8 = read_gnutella8()
    gnutella9 = read_gnutella9()
    c_arr = [0.9, 0.85, 0.75, 0.6, 0.5]
    
    e8_1 = np.random.dirichlet(np.ones(gnutella8.shape[1]),size=1)
    e8_2 = np.random.dirichlet(np.ones(gnutella8.shape[1])/1000,size=1)
    e8_3 = np.random.dirichlet(np.ones(gnutella8.shape[1])*1000,size=1)
    e8 = [e8_1, e8_2, e8_3]
    
    e9_1 = np.random.dirichlet(np.ones(gnutella9.shape[1]),size=1)
    e9_2 = np.random.dirichlet(np.ones(gnutella9.shape[1])/1000,size=1)
    e9_3 = np.random.dirichlet(np.ones(gnutella9.shape[1])*1000,size=1)
    e9 = [e9_1, e9_2, e9_3]
    
    np.set_printoptions(suppress=True)
    
    for c in c_arr:
        for e in e8:
            print(page_rank(gnutella8, e,10e-1,c))
            
    for c in c_arr:
        for e in e9:
            print(page_rank(gnutella9, e,10e-1,c))
        
test_page_rank()


[[0.01586993 0.00984567 0.00035583 ... 0.01007556 0.0024574  0.00081789]]
[[0.00052431 0.         0.         ... 0.         0.         0.        ]]
[[0.02005959 0.00701793 0.00766049 ... 0.0067199  0.00768772 0.00756953]]
[[0.01926633 0.01008476 0.00036447 ... 0.01032024 0.00251708 0.00083775]]
[[0.00052366 0.         0.         ... 0.         0.         0.        ]]
[[0.0183888  0.00714353 0.00779759 ... 0.00684017 0.00782531 0.007705  ]]
[[0.01760401 0.01065748 0.00038517 ... 0.01090633 0.00266002 0.00088533]]
[[0.00033793 0.         0.         ... 0.         0.         0.        ]]
[[0.01884788 0.00777824 0.0084904  ... 0.00744792 0.00852059 0.00838958]]
[[0.01625287 0.01140556 0.0004122  ... 0.01167187 0.00284674 0.00094747]]
[[0.00036513 0.         0.         ... 0.         0.         0.        ]]
[[0.01533423 0.00852984 0.00931082 ... 0.0081676  0.00934393 0.00920026]]
[[0.01709421 0.01187277 0.00042909 ... 0.01215    0.00296335 0.00098629]]
[[0.00024762 0.         0.         ...

<h6>Wnioski</h6>
1.Bładzenie losowe szereguje strony internetowe<br>
2.Algorytm PageRank pozwala również uszeregować strony internetowe<br>
3.PageRank pozwala wykorzystać możliwość skoku do losowego wierzchołka, co wpływa na uporządkowanie stron<br>
